In [411]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [412]:
df = pd.read_csv('train.csv')

In [413]:
df.head()

id  Gender        Age    Height      Weight family_history_with_overweight   
0   0    Male  24.443011  1.699998   81.669950                            yes  \
1   1  Female  18.000000  1.560000   57.000000                            yes   
2   2  Female  18.000000  1.711460   50.165754                            yes   
3   3  Female  20.952737  1.710730  131.274851                            yes   
4   4    Male  31.641081  1.914186   93.798055                            yes   

  FAVC      FCVC       NCP        CAEC SMOKE      CH2O SCC       FAF   
0  yes  2.000000  2.983297   Sometimes    no  2.763573  no  0.000000  \
1  yes  2.000000  3.000000  Frequently    no  2.000000  no  1.000000   
2  yes  1.880534  1.411685   Sometimes    no  1.910378  no  0.866045   
3  yes  3.000000  3.000000   Sometimes    no  1.674061  no  1.467863   
4  yes  2.679664  1.971472   Sometimes    no  1.979848  no  1.967973   

        TUE       CALC                 MTRANS           NObeyesdad  
0  0.976473  Sometimes  Public_Transportation  Overweight_Level_II  
1  1.000000         no             Automobile        Normal_Weight  
2  1.673584         no  Public_Transportation  Insufficient_Weight  
3  0.780199  Sometimes  Public_Transportation     Obesity_Type_III  
4  0.931721  Sometimes  Public_Transportation  Overweight_Level_II

In [414]:
df.describe()

id           Age        Height        Weight          FCVC   
count  20758.00000  20758.000000  20758.000000  20758.000000  20758.000000  \
mean   10378.50000     23.841804      1.700245     87.887768      2.445908   
std     5992.46278      5.688072      0.087312     26.379443      0.533218   
min        0.00000     14.000000      1.450000     39.000000      1.000000   
25%     5189.25000     20.000000      1.631856     66.000000      2.000000   
50%    10378.50000     22.815416      1.700000     84.064875      2.393837   
75%    15567.75000     26.000000      1.762887    111.600553      3.000000   
max    20757.00000     61.000000      1.975663    165.057269      3.000000   

                NCP          CH2O           FAF           TUE  
count  20758.000000  20758.000000  20758.000000  20758.000000  
mean       2.761332      2.029418      0.981747      0.616756  
std        0.705375      0.608467      0.838302      0.602113  
min        1.000000      1.000000      0.000000      0.000000  
25%        3.000000      1.792022      0.008013      0.000000  
50%        3.000000      2.000000      1.000000      0.573887  
75%        3.000000      2.549617      1.587406      1.000000  
max        4.000000      3.000000      3.000000      2.000000

In [415]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              20758 non-null  int64  
 1   Gender                          20758 non-null  object 
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  object 
 6   FAVC                            20758 non-null  object 
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object 
 10  SMOKE                           20758 non-null  object 
 11  CH2O                            20758 non-null  float64
 12  SCC                             

In [416]:
df['Gender'].value_counts()

Gender
Female    10422
Male      10336
Name: count, dtype: int64

In [417]:
def gender_to_numeric(data):
    if (data == "Male"):
        return 1
    else:
        return 2
    
# male is 1 and female is 2

In [418]:
df['Gender'] = df['Gender'].apply(gender_to_numeric)

In [419]:
df.head()

id  Gender        Age    Height      Weight family_history_with_overweight   
0   0       1  24.443011  1.699998   81.669950                            yes  \
1   1       2  18.000000  1.560000   57.000000                            yes   
2   2       2  18.000000  1.711460   50.165754                            yes   
3   3       2  20.952737  1.710730  131.274851                            yes   
4   4       1  31.641081  1.914186   93.798055                            yes   

  FAVC      FCVC       NCP        CAEC SMOKE      CH2O SCC       FAF   
0  yes  2.000000  2.983297   Sometimes    no  2.763573  no  0.000000  \
1  yes  2.000000  3.000000  Frequently    no  2.000000  no  1.000000   
2  yes  1.880534  1.411685   Sometimes    no  1.910378  no  0.866045   
3  yes  3.000000  3.000000   Sometimes    no  1.674061  no  1.467863   
4  yes  2.679664  1.971472   Sometimes    no  1.979848  no  1.967973   

        TUE       CALC                 MTRANS           NObeyesdad  
0  0.976473  Sometimes  Public_Transportation  Overweight_Level_II  
1  1.000000         no             Automobile        Normal_Weight  
2  1.673584         no  Public_Transportation  Insufficient_Weight  
3  0.780199  Sometimes  Public_Transportation     Obesity_Type_III  
4  0.931721  Sometimes  Public_Transportation  Overweight_Level_II

In [420]:
df['family_history_with_overweight'].value_counts()

family_history_with_overweight
yes    17014
no      3744
Name: count, dtype: int64

In [421]:
def family_history_with_overweight_to_numeric(data):
    if (data == "yes"):
        return 1
    else:
        return 2
# yes means overweight and no means not overweight, yes is 1 and no is 2

In [422]:
df['family_history_with_overweight'] = df['family_history_with_overweight'].apply(family_history_with_overweight_to_numeric)

In [423]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight FAVC      FCVC       NCP        CAEC SMOKE   
0                               1  yes  2.000000  2.983297   Sometimes    no  \
1                               1  yes  2.000000  3.000000  Frequently    no   
2                               1  yes  1.880534  1.411685   Sometimes    no   
3                               1  yes  3.000000  3.000000   Sometimes    no   
4                               1  yes  2.679664  1.971472   Sometimes    no   

       CH2O SCC       FAF       TUE       CALC                 MTRANS   
0  2.763573  no  0.000000  0.976473  Sometimes  Public_Transportation  \
1  2.000000  no  1.000000  1.000000         no             Automobile   
2  1.910378  no  0.866045  1.673584         no  Public_Transportation   
3  1.674061  no  1.467863  0.780199  Sometimes  Public_Transportation   
4  1.979848  no  1.967973  0.931721  Sometimes  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [424]:
df['FAVC'].value_counts()

FAVC
yes    18982
no      1776
Name: count, dtype: int64

In [425]:
def FAVC_to_numeric(data):
    if (data == "yes"):
        return 1
    else:
        return 2
#  frequency of consumption of high caloric food is 1 is yes and 2 is no

In [426]:
df['FAVC'] = df['FAVC'].apply(FAVC_to_numeric)

In [427]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP        CAEC SMOKE   
0                               1     1  2.000000  2.983297   Sometimes    no  \
1                               1     1  2.000000  3.000000  Frequently    no   
2                               1     1  1.880534  1.411685   Sometimes    no   
3                               1     1  3.000000  3.000000   Sometimes    no   
4                               1     1  2.679664  1.971472   Sometimes    no   

       CH2O SCC       FAF       TUE       CALC                 MTRANS   
0  2.763573  no  0.000000  0.976473  Sometimes  Public_Transportation  \
1  2.000000  no  1.000000  1.000000         no             Automobile   
2  1.910378  no  0.866045  1.673584         no  Public_Transportation   
3  1.674061  no  1.467863  0.780199  Sometimes  Public_Transportation   
4  1.979848  no  1.967973  0.931721  Sometimes  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [428]:
df['CAEC'].value_counts()

CAEC
Sometimes     17529
Frequently     2472
Always          478
no              279
Name: count, dtype: int64

In [429]:
# Consumption of food between meals
def CAEC_to_numeric(data):
    if (data == "no"):
        return 1
    elif (data == "Sometimes"):
        return 2
    elif (data == "Frequently"):
        return 3
    else:
        return 4

In [430]:
df['CAEC'] = df['CAEC'].apply(CAEC_to_numeric)

In [431]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC SMOKE   
0                               1     1  2.000000  2.983297     2    no  \
1                               1     1  2.000000  3.000000     3    no   
2                               1     1  1.880534  1.411685     2    no   
3                               1     1  3.000000  3.000000     2    no   
4                               1     1  2.679664  1.971472     2    no   

       CH2O SCC       FAF       TUE       CALC                 MTRANS   
0  2.763573  no  0.000000  0.976473  Sometimes  Public_Transportation  \
1  2.000000  no  1.000000  1.000000         no             Automobile   
2  1.910378  no  0.866045  1.673584         no  Public_Transportation   
3  1.674061  no  1.467863  0.780199  Sometimes  Public_Transportation   
4  1.979848  no  1.967973  0.931721  Sometimes  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [432]:
df['SMOKE'].value_counts()

SMOKE
no     20513
yes      245
Name: count, dtype: int64

In [433]:
def smoke_to_numeric(data):
    if (data == "yes"):
        return 1
    else:
        return 2
# 1 is yes and 2 is no

In [434]:
df['SMOKE'] = df['SMOKE'].apply(smoke_to_numeric)

In [435]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O SCC       FAF       TUE       CALC                 MTRANS   
0  2.763573  no  0.000000  0.976473  Sometimes  Public_Transportation  \
1  2.000000  no  1.000000  1.000000         no             Automobile   
2  1.910378  no  0.866045  1.673584         no  Public_Transportation   
3  1.674061  no  1.467863  0.780199  Sometimes  Public_Transportation   
4  1.979848  no  1.967973  0.931721  Sometimes  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [436]:
df['SCC'].value_counts()

SCC
no     20071
yes      687
Name: count, dtype: int64

In [437]:
def SCC_to_numeric(data):
    if (data == "yes"):
        return 1
    else:
        return 2
# 1 is yes and 2 is no

In [438]:
df['SCC'] = df['SCC'].apply(SCC_to_numeric)

In [439]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O  SCC       FAF       TUE       CALC                 MTRANS   
0  2.763573    2  0.000000  0.976473  Sometimes  Public_Transportation  \
1  2.000000    2  1.000000  1.000000         no             Automobile   
2  1.910378    2  0.866045  1.673584         no  Public_Transportation   
3  1.674061    2  1.467863  0.780199  Sometimes  Public_Transportation   
4  1.979848    2  1.967973  0.931721  Sometimes  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [440]:
df['CALC'].value_counts()

CALC
Sometimes     15066
no             5163
Frequently      529
Name: count, dtype: int64

In [441]:
def CALC_to_numeric(data):
    if (data == "no"):
        return 1
    elif (data == "Sometimes"):
        return 2
    elif (data == "Frequently"):
        return 3
    else:
        return 4

In [442]:
df['CALC'] = df['CALC'].apply(CALC_to_numeric)

In [443]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O  SCC       FAF       TUE  CALC                 MTRANS   
0  2.763573    2  0.000000  0.976473     2  Public_Transportation  \
1  2.000000    2  1.000000  1.000000     1             Automobile   
2  1.910378    2  0.866045  1.673584     1  Public_Transportation   
3  1.674061    2  1.467863  0.780199     2  Public_Transportation   
4  1.979848    2  1.967973  0.931721     2  Public_Transportation   

            NObeyesdad  
0  Overweight_Level_II  
1        Normal_Weight  
2  Insufficient_Weight  
3     Obesity_Type_III  
4  Overweight_Level_II

In [444]:
df['MTRANS'].value_counts()

MTRANS
Public_Transportation    16687
Automobile                3534
Walking                    467
Motorbike                   38
Bike                        32
Name: count, dtype: int64

In [445]:
def MTRANS_to_numeric(data):
    if (data == "Public_Transportation"):
        return 1
    elif (data == "Automobile"):
        return 2
    elif (data == "Motorbike"):
        return 3
    elif (data == "Bike"):
        return 4
    else:
        return 5

In [446]:
df['MTRANS'] = df['MTRANS'].apply(MTRANS_to_numeric)

In [447]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O  SCC       FAF       TUE  CALC  MTRANS           NObeyesdad  
0  2.763573    2  0.000000  0.976473     2       1  Overweight_Level_II  
1  2.000000    2  1.000000  1.000000     1       2        Normal_Weight  
2  1.910378    2  0.866045  1.673584     1       1  Insufficient_Weight  
3  1.674061    2  1.467863  0.780199     2       1     Obesity_Type_III  
4  1.979848    2  1.967973  0.931721     2       1  Overweight_Level_II

In [448]:
df['NObeyesdad'].value_counts()

NObeyesdad
Obesity_Type_III       4046
Obesity_Type_II        3248
Normal_Weight          3082
Obesity_Type_I         2910
Insufficient_Weight    2523
Overweight_Level_II    2522
Overweight_Level_I     2427
Name: count, dtype: int64

In [449]:
def NObeyesdad_to_numeric(data):
    if (data == "Insufficient_Weight"):
        return 0
    elif (data == "Normal_Weight"):
        return 1
    elif (data == "Overweight_Level_I"):
        return 2
    elif (data == "Overweight_Level_II"):
        return 3
    elif (data == "Obesity_Type_I"):
        return 4
    elif (data == "Obesity_Type_II"):
        return 5
    elif (data == "Obesity_Type_III"):
        return 6

In [450]:
df['NObeyesdad'] = df['NObeyesdad'].apply(NObeyesdad_to_numeric)

In [451]:
df.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O  SCC       FAF       TUE  CALC  MTRANS  NObeyesdad  
0  2.763573    2  0.000000  0.976473     2       1           3  
1  2.000000    2  1.000000  1.000000     1       2           1  
2  1.910378    2  0.866045  1.673584     1       1           0  
3  1.674061    2  1.467863  0.780199     2       1           6  
4  1.979848    2  1.967973  0.931721     2       1           3

In [452]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report,confusion_matrix
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.model_selection import cross_val_score
import xgboost as xgb

In [453]:
df.isna().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [454]:
df.dropna(inplace=True)

In [455]:
df.isna().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [456]:
X = df.drop(columns=['NObeyesdad'], axis=1)
y = df['NObeyesdad']

In [457]:
X.head()

id  Gender        Age    Height      Weight   
0   0       1  24.443011  1.699998   81.669950  \
1   1       2  18.000000  1.560000   57.000000   
2   2       2  18.000000  1.711460   50.165754   
3   3       2  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE   
0                               1     1  2.000000  2.983297     2      2  \
1                               1     1  2.000000  3.000000     3      2   
2                               1     1  1.880534  1.411685     2      2   
3                               1     1  3.000000  3.000000     2      2   
4                               1     1  2.679664  1.971472     2      2   

       CH2O  SCC       FAF       TUE  CALC  MTRANS  
0  2.763573    2  0.000000  0.976473     2       1  
1  2.000000    2  1.000000  1.000000     1       2  
2  1.910378    2  0.866045  1.673584     1       1  
3  1.674061    2  1.467863  0.780199     2       1  
4  1.979848    2  1.967973  0.931721     2       1

In [458]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [459]:
models = {
    'Random Forest': RandomForestClassifier(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Naive Bayes': GaussianNB(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'XGBoost': xgb.XGBClassifier()
}

In [460]:
from prettytable import PrettyTable


for model_name, model in models.items():
    # Fit the model
    model.fit(x_train, y_train)

    # Make predictions
    y_pred = model.predict(x_test)
    y_prob = model.predict_proba(x_test)[:,1]

    cr = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)

    # Evaluate performance
    accuracy = accuracy_score(y_test, y_pred)

    # Create a PrettyTable for the classification report
    report_table = PrettyTable()
    report_table.field_names = ['Class', 'Precision', 'Recall', 'F1-Score', 'Support']
    for class_name, metrics in cr.items():
        if class_name.isdigit():  # Skip non-numeric class names (if any)
            report_table.add_row([class_name,
                                  metrics['precision'],
                                  metrics['recall'],
                                  metrics['f1-score'],
                                  metrics['support']])

    # Print results
    print(f"Model: {model_name}")
    print(f"Confusion matrix:\n{cm}")
    print("-" * 40)
    print("Classification report:")
    print(report_table)
    print(f"Accuracy: {accuracy:.2f}")
    print("-" * 40)

Model: Random Forest
Confusion matrix:
[[484  37   2   1   0   0   0]
 [ 24 557  42   3   0   0   0]
 [  1  48 368  58   9   0   0]
 [  0  13  44 414  37   6   0]
 [  2   2  14  38 474  12   1]
 [  0   0   0   3  15 638   1]
 [  0   0   0   0   1   1 802]]
----------------------------------------
Classification report:
+-------+--------------------+--------------------+--------------------+---------+
| Class |     Precision      |       Recall       |      F1-Score      | Support |
+-------+--------------------+--------------------+--------------------+---------+
|   0   | 0.9471624266144814 | 0.9236641221374046 | 0.9352657004830918 |  524.0  |
|   1   |  0.84779299847793  | 0.889776357827476  | 0.8682774746687452 |  626.0  |
|   2   | 0.7829787234042553 | 0.7603305785123967 | 0.7714884696016772 |  484.0  |
|   3   | 0.8007736943907157 | 0.8054474708171206 | 0.8031037827352085 |  514.0  |
|   4   | 0.8843283582089553 | 0.8729281767955801 | 0.8785912882298424 |  543.0  |
|   5   | 0.971

In [461]:
model = GradientBoostingClassifier()

In [462]:
model.fit(x_train, y_train)

GradientBoostingClassifier()

In [463]:
y_pred = model.predict(x_test)

In [464]:
print(accuracy_score(y_test, y_pred))

0.903179190751445


In [465]:
df_test = pd.read_csv('test.csv')

In [466]:
df_test.head()

id  Gender        Age    Height      Weight   
0  20758    Male  26.899886  1.848294  120.644178  \
1  20759  Female  21.000000  1.600000   66.000000   
2  20760  Female  26.000000  1.643355  111.600553   
3  20761    Male  20.979254  1.553127  103.669116   
4  20762  Female  26.000000  1.627396  104.835346   

  family_history_with_overweight FAVC      FCVC       NCP       CAEC SMOKE   
0                            yes  yes  2.938616  3.000000  Sometimes    no  \
1                            yes  yes  2.000000  1.000000  Sometimes    no   
2                            yes  yes  3.000000  3.000000  Sometimes    no   
3                            yes  yes  2.000000  2.977909  Sometimes    no   
4                            yes  yes  3.000000  3.000000  Sometimes    no   

       CH2O SCC       FAF       TUE       CALC                 MTRANS  
0  2.825629  no  0.855400  0.000000  Sometimes  Public_Transportation  
1  3.000000  no  1.000000  0.000000  Sometimes  Public_Transportation  
2  2.621877  no  0.000000  0.250502  Sometimes  Public_Transportation  
3  2.786417  no  0.094851  0.000000  Sometimes  Public_Transportation  
4  2.653531  no  0.000000  0.741069  Sometimes  Public_Transportation

In [467]:
df_test['Gender'] = df_test['Gender'].apply(gender_to_numeric)
df_test['family_history_with_overweight'] = df_test['family_history_with_overweight'].apply(family_history_with_overweight_to_numeric)
df_test['FAVC'] = df_test['FAVC'].apply(FAVC_to_numeric)
df_test['CAEC'] = df_test['CAEC'].apply(CAEC_to_numeric)
df_test['SMOKE'] = df_test['SMOKE'].apply(smoke_to_numeric)
df_test['SCC'] = df_test['SCC'].apply(SCC_to_numeric)
df_test['CALC'] = df_test['CALC'].apply(CALC_to_numeric)
df_test['MTRANS'] = df_test['MTRANS'].apply(MTRANS_to_numeric)

In [468]:
df_test.isna().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
dtype: int64

In [469]:
pred = model.predict(df_test)

In [470]:
pred

array([5, 2, 6, ..., 0, 1, 5])

In [471]:
type(pred)

numpy.ndarray

In [472]:
import pandas as pd

# Assuming your ndarray is named "my_array"
df_no = pd.DataFrame(pred, columns=["NObeyesdad"])

# Print the dataframe
print(df_no)


       NObeyesdad
0               5
1               2
2               6
3               4
4               6
...           ...
13835           3
13836           2
13837           0
13838           1
13839           5

[13840 rows x 1 columns]


In [473]:
df_no.head()

NObeyesdad
0           5
1           2
2           6
3           4
4           6

In [474]:
def pred_inverse(df):
    if (df == 0):
        return "Insufficient_Weight"
    elif (df == 1):
        return "Normal_Weight"
    elif (df == 2):
        return "Overweight_Level_I"
    elif (df == 3):
        return "Overweight_Level_II"
    elif (df == 4):
        return "Obesity_Type_I"
    elif (df == 5):
        return "Obesity_Type_II"
    elif (df == 6):
        return "Obesity_Type_III"

In [475]:
df_no['NObeyesdad'] = df_no['NObeyesdad'].apply(pred_inverse)

In [476]:
submissions_df = pd.DataFrame({'id': df_test['id'], 'NObeyesdad': df_no['NObeyesdad']})

# Save the DataFrame to a CSV file named "submissions.csv" without index
submissions_df.to_csv('submissions.csv', index=False)

In [477]:
df_test.shape

(13840, 17)

In [478]:
from xgboost import XGBClassifier


model = XGBClassifier()

In [479]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.01, 0.001]
}

In [480]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(
    model,
    param_grid=param_grid,
    scoring='accuracy',  
    cv=5,  
    n_jobs=-1
)

In [481]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.01, 0.001],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [482]:
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

In [483]:
best_params

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 300}

In [484]:
model_tuned = XGBClassifier(**best_params)

In [485]:
model_tuned.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [486]:
y_pred = model_tuned.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.91


In [487]:
pred = model_tuned.predict(df_test)

In [488]:
import pandas as pd

# Assuming your ndarray is named "my_array"
df_no = pd.DataFrame(pred, columns=["NObeyesdad"])

# Print the dataframe
print(df_no)


       NObeyesdad
0               5
1               2
2               6
3               4
4               6
...           ...
13835           3
13836           2
13837           0
13838           1
13839           5

[13840 rows x 1 columns]


In [489]:
df_no['NObeyesdad'] = df_no['NObeyesdad'].apply(pred_inverse)

In [490]:
submissions_df = pd.DataFrame({'id': df_test['id'], 'NObeyesdad': df_no['NObeyesdad']})

# Save the DataFrame to a CSV file named "submissions.csv" without index
submissions_df.to_csv('submissions.csv', index=False)